apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manual
spec:
  rules:
    - http:
        paths:
          - path: /manual-staging(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: manual-staging
                port:
                  number: 3000