# For Preview Environments a ApplicationSet is used, because the application for each pull request
# must be created with dynamic information such as the number and the name of the pull request.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preview-environments-appset
  namespace: argocd
spec:
  generators:
    - pullRequest:
        # Set the reconciliation time for watching PRs to 15 seconds to increase feedback times
        requeueAfterSeconds: 15
        github:
          owner: lukma99
          repo: gitops-test-env
          # Use credentials even though it is a public repository to avoid rate limits by GitHub
          tokenRef:
            secretName: github-repo-creds
            key: password
          # Only watch PRs with label "preview" to avoid creating a preview environment for ALL PRs
          labels:
            - preview
  template:
    metadata:
      name: 'preview-environment-{{branch_slug}}-{{number}}' # Guarantee uniqueness by combining name of branch and PR number
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: 'preview-{{branch_slug}}-{{number}}'
      project: default
      source:
        repoURL: https://github.com/lukma99/gitops-test-env.git
        path: k8s-deployments/05-preview-environments/overlays/preview
        targetRevision: '{{head_sha}}'
        kustomize:
          commonLabels:
            app.kubernetes.io/instance: '{{branch_slug}}-{{number}}'
          commonAnnotations: # Path for URL and Namespace have to be delegated by Kustomize Replacement mechanism
            app/param-path: /preview-{{branch_slug}}-{{number}}
            app/param-namespace: preview-{{branch_slug}}-{{number}}
          images:
            - 'ghcr.io/lukma99/gitops-test-env:{{head_sha}}' # This image is created on opening a feature PR by GitHub Action
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
