apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dependency-bot
spec:
  rules:
    - http:
        paths:
          - path: /dependency-bot-dev
            pathType: Prefix
            backend:
              service:
                name: dependency-bot-dev
                port:
                  number: 3000