apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging
nameSuffix: -staging

commonLabels:
  app.kubernetes.io/name: image-updater-staging

resources:
  - ../../base

patchesStrategicMerge:
  - replicas.yaml
  - volumeMount.yaml
  - ingress.yaml
  - configmap.yaml

# Image Name and Tag will is stored in ".argocd-source-image-updater-STAGE.yaml" instead of here,
# so that Argo CD knows to pick it up and Image Updater can update the version using git-writeback