apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: prod
# nameSuffix: -prod

# commonLabels:
#   app.kubernetes.io/name: preview-environment

resources:
  - ../../base

patchesStrategicMerge:
  - replicas.yaml
  - ingress.yaml
  - configmap.yaml
#- volumeMount.yaml is not needed like in the other cases, because there are no suffixes to change in the names


replacements:
  - path: replacement-path.yaml
  - path: replacement-namespace.yaml

#images:
#  - name: ghcr.io/lukma99/gitops-test-env
#    newTag: 2.1.1