apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - replicas.yaml
  - ingress.yaml
  - configmap.yaml
#- volumeMount.yaml is not needed like in the other cases, because there are no suffixes to change in the names


replacements:
  - path: replacement-path.yaml
  - path: replacement-namespace.yaml

# Image Name and Tag is specified dynamically by the Pull Request Generator from the ApplicationSet instead of here.