apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ci-pipeline
spec:
  rules:
    - http:
        paths:
          - path: /ci-pipeline-prod(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: ci-pipeline-prod
                port:
                  number: 3000