apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
nameSuffix: -staging
commonLabels:
  app.kubernetes.io/name: ci-pipeline-staging
resources:
  - ../../base
patchesStrategicMerge:
  - replicas.yaml
  - volumeMount.yaml
  - ingress.yaml
  - configmap.yaml
images:
  - name: ghcr.io/lukma99/gitops-test-env
    newTag: 1.0.3
