apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: image-updater
spec:
  rules:
    - http:
        paths:
          - path: /image-updater-dev
            pathType: Prefix
            backend:
              service:
                name: image-updater-dev
                port:
                  number: 3000