apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dependency-bot-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/lukma99/gitops-test-env
    path: k8s-deployments/04-dependency-bot/overlays/prod
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true