name: Build and Push Docker Image

on:
  # Run pipeline manually to release new image version
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker Tag'
        required: true
        type: string
  # Run pipeline on PR to release image for preview environment
  pull_request:
    branches:    
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'workflow_dispatch' || ( !(startsWith(github.event.pull_request.head.ref, 'renovate/')) && !(startsWith(github.event.pull_request.head.ref, 'pipeline/')) ) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Reponame has to be set to lowercase, because Docker commands fail when providing registry links with uppercase characters
      - name: Set reponame to lowercase and export as IMAGE_NAME
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Login to Docker Registry
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $REGISTRY_PASSWORD | docker login ghcr.io -u $REGISTRY_USER --password-stdin

      # Uses semver tag which the user specified on manual run
      - name: Build Docker Image (Manual Action Run)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          IMAGE_TAG: ${{ inputs.docker_tag }}
        run: |
          docker build \
            --build-arg DOCKER_TAG=${IMAGE_TAG} \
            --tag ghcr.io/${IMAGE_NAME}:${IMAGE_TAG} \
            --tag ghcr.io/${IMAGE_NAME}:latest \
            --label "org.opencontainers.image.source=https://github.com/${IMAGE_NAME}" \
            ./app

      # Uses SHA of the head of the new branch to ensure a unique tag for preview environments
      - name: Build Docker Image (Pull Request)
        if: ${{ github.event_name == 'pull_request' }}
        env:
          IMAGE_TAG: ${{ github.event.pull_request.head.sha }}
        run: |
          docker build \
            --build-arg DOCKER_TAG=${IMAGE_TAG} \
            --tag ghcr.io/${IMAGE_NAME}:${IMAGE_TAG} \
            --label "org.opencontainers.image.source=https://github.com/${IMAGE_NAME}" \
            ./app
          
      - name: Push Docker Image
        env:
          IMAGE_TAG: ${{ inputs.docker_tag }}
        run: |
          docker push --all-tags ghcr.io/${IMAGE_NAME}
          mkdir ./image
          echo ${IMAGE_TAG} > ./image/image_tag

      # Artefact only contains the tag of the image, so that the deploy-pipeline.yaml Action knows which tag to deploy
      - uses: actions/upload-artifact@v3
        with:
          name: image_tag
          path: image/
