name: Build and Push Docker Image

on:
  # run pipeline manually
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker Tag'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Registry
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GH_TOKEN }}
        run: |
          echo $REGISTRY_PASSWORD | docker login ghcr.io -u $REGISTRY_USER --password-stdin

      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: ${{ github.repository }}
          IMAGE_TAG: ${{ inputs.docker_tag }}
        run: |
          docker build \
            --tag ghcr.io/${IMAGE_NAME}:${IMAGE_TAG} \
            --label "org.opencontainers.image.source=https://github.com/${IMAGE_NAME}" \
            ./app
          docker push ghcr.io/${IMAGE_NAME}:${IMAGE_TAG}