name: Renovate Bot
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
    - completed
#  schedule:
#    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v38.1.1
        with:
          configurationFile: .github/renovate.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
